export const reportLabels = {
  title: "LLM Evaluator Report",
  darkMode: "Dark Mode",
  executionInfo: "Execution Info",
  currentExecution: "Current Execution",
  executionDate: "Execution Date",
  executionId: "Execution ID",
  executedAt: "Executed At",
  provider: "Provider",
  model: "Model",
  appliedFilters: "Applied Filters",
  filters: "Filters",
  executionDuration: "Execution Duration",
  qualityGate: "Quality Gate",
  qualityGateDisabled: "Quality Gate: Disabled",
  successRateGate: "Success Rate Gate",
  avgScoreGate: "Avg Score Gate",
  failCountGate: "Fail Count Gate",
  errorCountGate: "Error Count Gate",
  regressionCountGate: "Regression Count Gate",
  criticalFailuresGate: "Critical Failures Gate",
  summary: "Summary",
  totalScenarios: "Total Scenarios",
  pass: "PASS",
  fail: "FAIL",
  error: "ERROR",
  missingResponses: "Missing Responses",
  successRate: "Success Rate",
  averageScore: "Average Score",
  averageResponseTime: "Average Response Time",
  mockResponseTime: "N/A (Mock Provider)",
  comparison: "Comparison with Previous Execution",
  currentSuccessRate: "Current Success Rate",
  previousSuccessRate: "Previous Success Rate",
  successRateDelta: "Success Rate Delta",
  currentAvgScore: "Current Avg Score",
  previousAvgScore: "Previous Avg Score",
  avgScoreDelta: "Avg Score Delta",
  regressions: "Regressions",
  improvements: "Improvements",
  newScenarios: "New Scenarios",
  removedScenarios: "Removed Scenarios",
  executionHistory: "Execution History",
  showHistory: "Show History",
  hideHistory: "Hide History",
  noPreviousExecution: "No previous execution available for comparison yet.",
  noExecutionHistory: "No execution history available yet.",
  noScenariosForFilters: "No scenarios found for the applied filters.",
  noScenariosExecuted: "No scenarios executed.",
  allScenariosPassed: "All scenarios passed. No failures detected.",
  allScenariosPassedChart: "All scenarios passed. 100%",
  allScenariosFailed: "All scenarios failed quality validations.",
  noTechnicalErrors: "No technical errors detected.",
  averageScoreMaximum: "Average score is at maximum.",
  quality: "Quality",
  score: "Score",
  qualityFailures: "Quality Failures",
  technicalErrors: "Technical Errors",
  mostAffectedCategory: "Most Affected Category",
  highestFailCategory: "Highest FAIL Category",
  mostAffectedValidator: "Most Affected Validator",
  mostFrequentErrorType: "Most Frequent Error Type",
  statusChart: "PASS x FAIL x ERROR",
  statusByCategoryChart: "Status by Category",
  scenariosByCategoryChart: "Scenarios by Category",
  scoreDistributionChart: "Score Distribution",
  allCategoriesSingleScenario: "All categories have only 1 scenario.",
  noScoreData: "No score data available.",
  insights: "Insights",
  scenarios: "Scenarios",
  scenarioResults: "Scenario Results",
  scenarioDetails: "Scenario Details",
  details: "Details",
  idTitle: "ID / Title",
  category: "Category",
  priority: "Priority",
  severity: "Severity",
  timeMs: "Time (ms)",
  overallStatus: "Overall Status",
  errorType: "Error Type",
  searchById: "Search by ID",
  searchByCategory: "Search by Category",
  pageSize10: "10 per page",
  pageSize25: "25 per page",
  pageSize50: "50 per page",
  pageSize100: "100 per page",
  previous: "Previous",
  next: "Next",
  page: "Page",
  of: "of",
  input: "Input",
  response: "Response",
  expectedCriteria: "Expected Criteria",
  validationResults: "Validation Results",
  diagnostics: "Diagnostics",
  fullPrompt: "Full Prompt",
  fullAiResponse: "Full AI Response",
  showMore: "Show more",
  inputTokens: "Input Tokens",
  outputTokens: "Output Tokens",
  expectedRegex: "Expected Regex",
  expectedIntent: "Expected Intent",
  expectedEntity: "Expected Entity",
  feature: "Feature",
  requirementId: "Requirement ID",
  tags: "Tags",
  regexStatus: "Regex Status",
  intentStatus: "Intent Status",
  entityStatus: "Entity Status",
  errorMessage: "Error Message"
} as const;
